# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_brand_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandtext',
            name='brand',
        ),
        migrations.DeleteModel(
            name='BrandText',
        ),
    ]
